"""
Marker parsing and merging for generated documentation content.

Every generated section is wrapped in its own marker pair so that
sections can be generated, updated, or removed independently. A
section block looks like::

    <!-- Start - Generated By Treeva [<section name>], Don't edit this section manually -->
    <!-- End - Generated By Treeva -->
"""

from __future__ import annotations

import re
from dataclasses import dataclass

END_MARKER = "<!-- End - Generated By Treeva -->"

_NAMED_START_RE = re.compile(
    r"^<!-- Start - Generated By Treeva \[([a-z0-9-]+)\], "
    r"Don't edit this section manually -->$"
)


@dataclass(frozen=True)
class SectionBlock:
    """A generated section block found in a file.

    Attributes:
        section: Section name.
        start: Line index of the START marker.
        end: Line index of the END marker (inclusive).
    """

    section: str
    start: int
    end: int


def section_start_marker(section: str) -> str:
    """Build the START marker line for a named section."""
    return (
        f"<!-- Start - Generated By Treeva [{section}], "
        "Don't edit this section manually -->"
    )


def render_blocks(sections: list[tuple[str, list[str]]]) -> str:
    """Render a sequence of (section, content) pairs as marker blocks.

    Blocks are joined with a blank line so adjacent markers stay
    readable in the generated file.

    Args:
        sections: Ordered pairs of section name and content lines
            (without markers).

    Returns:
        Full block text including the markers.
    """
    blocks = []
    for name, lines in sections:
        block = "\n".join([section_start_marker(name), *lines, END_MARKER])
        blocks.append(block)
    return "\n\n".join(blocks)


def parse_blocks(content: str) -> list[SectionBlock]:
    """Find all generated marker blocks in a file's content.

    Orphan END markers (without a matching START) are ignored.

    Args:
        content: Full file content.

    Returns:
        List of blocks in file order, each with line indices into
        the original content.
    """
    blocks: list[SectionBlock] = []
    open_start: int | None = None
    open_section = ""

    for i, line in enumerate(content.split("\n")):
        stripped = line.strip()
        match = _NAMED_START_RE.match(stripped)
        if match:
            open_start = i
            open_section = match.group(1)
            continue
        if stripped == END_MARKER and open_start is not None:
            blocks.append(
                SectionBlock(section=open_section, start=open_start, end=i)
            )
            open_start = None
            open_section = ""

    return blocks


def merge_sections(existing: str, sections: dict[str, str]) -> str | None:
    """Merge newly rendered sections into an existing generated file.

    Replaces the blocks of requested sections in place, appends
    requested sections that have no block yet, and preserves all
    unmanaged text outside the generated blocks.

    Args:
        existing: Current file content.
        sections: Mapping of section name to new rendered block text.

    Returns:
        The merged content, or None when the file contains no
        generated blocks at all (caller decides how to handle that).
    """
    blocks = parse_blocks(existing)
    if not blocks:
        return None

    lines = existing.split("\n")
    out: list[str] = []
    cursor = 0
    written: set[str] = set()

    for block in blocks:
        if block.start > cursor:
            out.extend(lines[cursor : block.start])
        segment = lines[block.start : block.end + 1]
        if block.section in sections:
            out.append(sections[block.section])
            written.add(block.section)
        else:
            out.extend(segment)
        cursor = block.end + 1

    missing = [(name, text) for name, text in sections.items() if name not in written]
    if missing:
        if cursor < len(lines) and lines[cursor].strip() == "":
            cursor += 1
        if out and out[-1] != "":
            out.append("")
        out.append("\n\n".join(text for _, text in missing))

    if cursor < len(lines):
        out.extend(lines[cursor:])

    return "\n".join(out) + "\n"


def remove_sections(content: str, sections: set[str]) -> tuple[str, bool]:
    """Remove generated section blocks from a file's content.

    Args:
        content: Full file content.
        sections: Section names whose blocks should be removed.

    Returns:
        A tuple of (new_content, removed_any) where removed_any is
        True when at least one block was removed.
    """
    blocks = parse_blocks(content)
    if not blocks:
        return content, False

    lines = content.split("\n")
    out: list[str] = []
    cursor = 0
    removed = False

    for block in blocks:
        if block.start > cursor:
            out.extend(lines[cursor : block.start])
        if block.section in sections:
            removed = True
        else:
            out.extend(lines[block.start : block.end + 1])
        cursor = block.end + 1

    if cursor < len(lines):
        out.extend(lines[cursor:])

    return "\n".join(out), removed