from .enums import Files


FILE_EXTENSIONS: dict[Files, list[str]] = {
    Files.PYTHON: [".py"],
    Files.JAVASCRIPT: [".js", ".jsx"],
    Files.TYPESCRIPT: [".ts", ".tsx"],
    Files.JAVA: [".java"],
    Files.CPP: [".cpp", ".hpp", ".cc", ".cxx"],
    Files.C: [".c", ".h"],
    Files.CSHARP: [".cs"],
    Files.GO: [".go"],
    Files.RUST: [".rs"],
    Files.RUBY: [".rb"],
    Files.PHP: [".php"],
    Files.SWIFT: [".swift"],
    Files.KOTLIN: [".kt", ".kts"],
    Files.SCALA: [".scala"],
    Files.GROOVY: [".groovy"],
    Files.PERL: [".pl"],
    Files.R: [".r"],
    Files.LUA: [".lua"],
    Files.DART: [".dart"],
    Files.ELIXIR: [".ex", ".exs"],
    Files.CLOJURE: [".clj", ".cljs"],
    Files.HASKELL: [".hs"],
    Files.OCAML: [".ml", ".mli"],
    Files.HTML: [".html", ".htm"],
    Files.CSS: [".css"],
    Files.SCSS: [".scss"],
    Files.SASS: [".sass"],
    Files.LESS: [".less"],
    Files.SQL: [".sql"],
    Files.BASH: [".sh"],
    Files.ZSH: [".zsh"],
    Files.FISH: [".fish"],
    Files.POWERSHELL: [".ps1"],
    Files.QML: [".qml"],
    Files.JSON: [".json"],
    Files.YAML: [".yaml", ".yml"],
    Files.TOML: [".toml"],
    Files.XML: [".xml"],
    Files.INI: [".ini", ".cfg", ".conf"],
    Files.PROPERTIES: [".properties"],
    Files.ENV: [".env"],
    Files.MARKDOWN: [".md"],
    Files.RST: [".rst"],
    Files.LATEX: [".tex"],
    Files.ASCIIDOC: [".adoc"],
    Files.ORG: [".org"],
    Files.TXT: [".txt"],
    Files.LOG: [".log"],
}


DEFAULT_EXCLUDES: set[str] = {
    # Version control
    ".git",
    ".svn",
    ".hg",
    ".bzr",
    # Python
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".nox",
    ".venv",
    "venv",
    "env",
    ".env",
    "site-packages",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    # Node / JavaScript / TypeScript
    "node_modules",
    ".npm",
    ".pnpm-store",
    ".yarn",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".parcel-cache",
    ".turbo",
    "coverage",
    # Java / Kotlin / Gradle
    ".gradle",
    "build",
    "out",
    "target",
    # Go / PHP / Ruby
    "vendor",
    ".bundle",
    "vendor/bundle",
    # C / C++ / CMake
    "cmake-build-debug",
    "cmake-build-release",
    "CMakeFiles",
    "CMakeCache.txt",
    "compile_commands.json",
    "Makefile",
    "*.o",
    "*.obj",
    "*.so",
    "*.dll",
    "*.exe",
    "*.a",
    "*.lib",
    # Swift / Xcode
    ".build",
    "DerivedData",
    # Dart / Flutter
    ".dart_tool",
    ".flutter-plugins",
    ".flutter-plugins-dependencies",
    ".packages",
    # Android / .NET
    ".idea",
    "captures",
    "bin",
    "obj",
    ".vs",
    # IDEs / Editors
    ".vscode",
    "*.iml",
    "*.suo",
    "*.user",
    "*.swp",
    "*.swo",
    "*~",
    # OS junk
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
    # Logs / temp
    "*.log",
    "*.tmp",
    "*.temp",
    "tmp",
    "temp",
    # Caches
    ".cache",
    ".sass-cache",
    ".eslintcache",
    # Distribution / build output
    "dist",
    "release",
    "debug",
    # Misc
    ".history",
}
