"""Generate AGENTS.md reference files for projects.

Walks the project tree, analyzes all source files, and produces
structured AGENTS.md documentation for the root and each subdirectory.
"""

from __future__ import annotations
from typing import TYPE_CHECKING
from collections import defaultdict
from pathlib import Path

if TYPE_CHECKING:
    from logging import Logger

from treeva.analysis import (
    analyze_file,
    extract_file_symbols,
    file_info_from_path,
)
from treeva.scanners import dir_walker
from treeva.constants.enums import FileCategory
from treeva.library.exceptions import UnsupportedLanguage

START_MARKER = (
    "<!-- Start - Generated By Treeva, Don't edit this section manually -->"
)
END_MARKER = "<!-- End - Generated By Treeva -->"

_ROOT_DESCRIPTIONS: dict[str, str] = {
    "README.md": "Project description and documentation",
    "LICENSE.md": "License information",
    "CONTRIBUTING.md": "Contribution guidelines",
    "CHANGELOG.md": "Version history and changelog",
    "TODOS.md": "Task and TODO tracking",
    "pyproject.toml": "Python project metadata and dependencies",
    "uv.lock": "Lockfile for uv package manager",
    ".gitignore": "Git ignore rules",
    ".prettierrc": "Prettier code formatter configuration",
    ".python-version": "Python version specification",
}


def generate_agents_md(
    project_root: Path,
    *,
    logger: Logger,
    extra_exclude_patterns: list[str] | None = None,
) -> dict[str, str]:
    """Generate AGENTS.md content for every directory under project_root.

    Walks the project tree, analyzes all source files for metrics and
    symbols, and formats the results as AGENTS.md sections for the
    root directory and each subdirectory.

    Args:
        project_root: Root path of the project to analyze.
        logger: Logger instance for diagnostic output.
        extra_exclude_patterns: Additional glob patterns to exclude from scanning.

    Returns:
        A mapping from AGENTS.md file paths (relative to project_root)
        to their generated markdown content.
    """
    dir_files: dict[str, list[dict]] = defaultdict(list)
    total_loc = 0
    total_files = 0
    lang_loc: dict[str, int] = defaultdict(int)

    for path in dir_walker(
        project_root, extra_exclude_patterns=extra_exclude_patterns
    ):
        if not path.is_file():
            continue
        total_files += 1

        sf = file_info_from_path(path)
        try:
            analysis = analyze_file(sf, logger=logger)
        except UnsupportedLanguage:
            analysis = None
        metrics = analysis.code_metrics if analysis else None
        symbols = [
            {
                "name": s.name,
                "kind": s.kind,
                "start": s.start_line,
                "end": s.end_line,
            }
            for s in extract_file_symbols(sf)
        ]

        rel = path.relative_to(project_root)
        parent = str(rel.parent) if rel.parent != Path(".") else "."

        loc = metrics.lines_of_code if metrics else 0
        comment_lines = metrics.lines_of_comment if metrics else 0
        blank_lines = metrics.blank_lines if metrics else 0
        if not metrics:
            try:
                loc = len(path.read_bytes().split(b"\n"))
            except Exception:
                loc = 0

        entry = {
            "filename": rel.name,
            "language": sf.file_type.label,
            "category": sf.file_type.category,
            "loc": loc,
            "comment_lines": comment_lines,
            "blank_lines": blank_lines,
            "comment_density": metrics.comment_density if metrics else 0.0,
            "functions": metrics.function_count if metrics else 0,
            "classes": metrics.class_count if metrics else 0,
            "imports": metrics.import_count if metrics else 0,
            "branches": metrics.branches_count if metrics else 0,
            "loops": metrics.loops_count if metrics else 0,
            "returns": metrics.returns_count if metrics else 0,
            "symbols": symbols,
        }
        dir_files[parent].append(entry)

        if metrics:
            total_loc += metrics.lines_of_code
            lang = sf.file_type.label
            lang_loc[lang] += metrics.lines_of_code

    result: dict[str, str] = {}
    dirs_sorted = sorted(dir_files.items(), key=lambda x: x[0])

    for dirpath, files in dirs_sorted:
        if dirpath == ".":
            continue
        content = _format_dir_agents(dirpath, files)
        result[f"{dirpath}/AGENTS.md"] = "\n".join(content)

    root_files = dir_files.get(".", [])
    all_dirs = sorted(
        (d for d in dir_files if d != "."),
        key=lambda d: d,
    )
    content = _format_root_agents(
        project_root,
        total_files,
        total_loc,
        lang_loc,
        root_files,
        all_dirs,
        dir_files,
    )
    result["AGENTS.md"] = "\n".join(content)

    return result


# ── Marker utilities ──


def split_at_markers(content: str) -> tuple[str, str, str]:
    """Split content around the generated START/END markers.

    Looks for START_MARKER and END_MARKER comment lines. If both markers
    are found in order, returns the content split into three parts.
    If markers are missing or out of order, returns the original content
    as ``pre`` with empty ``between`` and ``post``.

    Args:
        content: The full file content to split.

    Returns:
        A tuple of (pre, between, post) where pre is content before
        the start marker, between is content between markers (inclusive),
        and post is content after the end marker. If markers are not
        found correctly, returns (content, "", "").
    """
    lines = content.split("\n")
    start_idx = -1
    end_idx = -1
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped == START_MARKER:
            start_idx = i
        if stripped == END_MARKER:
            end_idx = i
            break

    if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
        pre = "\n".join(lines[:start_idx])
        between = "\n".join(lines[start_idx : end_idx + 1])
        post = "\n".join(lines[end_idx + 1 :])
        return pre, between, post

    return content, "", ""


def write_agents_file(
    output_path: Path,
    new_section: str,
    *,
    allow_overwrite: bool = False,
) -> bool:
    """Write a generated AGENTS.md section to disk, merging with existing content if present.

    If the file already exists, attempts to merge the new section between
    existing markers. If no markers are found, the behavior depends on
    ``allow_overwrite``: if True the new section is prepended; otherwise
    the write is refused and the function returns False.

    Args:
        output_path: Path where the AGENTS.md file should be written.
        new_section: The generated markdown content to write.
        allow_overwrite: Whether to overwrite a file that exists but
            has no markers.

    Returns:
        True if the file was written successfully, False if the file
        already existed without markers and ``allow_overwrite`` was False.
    """
    if output_path.exists():
        existing = output_path.read_text(encoding="utf-8")
        pre, between, post = split_at_markers(existing)
        has_markers = between != ""
        if has_markers:
            final = pre + "\n" + new_section + "\n" + post
        elif allow_overwrite:
            final = new_section + "\n" + existing
        else:
            return False
    else:
        final = new_section

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(final.strip() + "\n", encoding="utf-8")
    return True


# ── Formatting ──


def _wrap_section(lines: list[str]) -> list[str]:
    """Wrap content lines between start/end generator markers.

    Args:
        lines: Content lines to wrap.

    Returns:
        A new list with START_MARKER, the content lines, and END_MARKER.
    """
    return [START_MARKER, *lines, END_MARKER]


def _is_code_entry(entry: dict) -> bool:
    """Check if a file entry represents code or a script."""
    return entry["category"] in (FileCategory.CODE, FileCategory.SCRIPT)


def _lines_cell(entry: dict) -> str:
    """Format a file's line counts as a markdown table cell.

    Args:
        entry: A file entry dictionary with ``loc``, ``comment_lines``,
            and ``blank_lines`` keys.

    Returns:
        For code entries, a formatted string like ``"100 lines(80, 10, 10)"``.
        For non-code entries, the raw total line count as a string.
    """
    loc = entry["loc"]
    comments = entry["comment_lines"]
    blank = entry["blank_lines"]
    total = loc + comments + blank
    if _is_code_entry(entry):
        return f"{total} lines({loc}, {comments}, {blank})"
    return str(total)


def _category_label(entry: dict) -> str:
    """Return a human-readable label for a file's category.

    Args:
        entry: A file entry dictionary with a ``category`` key of type
            FileCategory.

    Returns:
        A human-readable label such as ``"Code"``, ``"Config"``, or ``"Doc"``.
    """
    cat = entry["category"]
    mapping = {
        FileCategory.CODE: "Code",
        FileCategory.SCRIPT: "Script",
        FileCategory.CONFIG: "Config",
        FileCategory.DOC: "Doc",
        FileCategory.OTHER: "Other",
    }
    return mapping.get(cat, "Other")


def _root_description(filename: str) -> str:
    """Look up the description for a well-known root file."""
    return _ROOT_DESCRIPTIONS.get(filename, "-")


def _build_file_tree(
    project_root: Path,
    dir_files: dict[str, list[dict]],
) -> list[str]:
    """Build an ASCII directory tree from the file map.

    Constructs a nested dictionary representing the project directory
    structure, then renders it as an ASCII tree inside a fenced code block.

    Args:
        project_root: Root path of the project (used for the tree label).
        dir_files: Mapping from directory path to list of file entries.

    Returns:
        Lines of the rendered ASCII directory tree including code fences.
    """
    tree: dict = {}
    for dirpath, files in dir_files.items():
        if dirpath == ".":
            for f in files:
                tree[f["filename"]] = None
        else:
            parts = dirpath.split("/")
            current = tree
            for part in parts:
                if part not in current:
                    current[part] = {}
                current = current[part]
            for f in files:
                current[f["filename"]] = None

    lines: list[str] = []
    lines.append("```")
    lines.append(f"{project_root.name}/")
    _render_tree(tree, lines, "")
    lines.append("```")
    return lines


def _render_tree(
    node: dict,
    lines: list[str],
    prefix: str,
):
    """Recursively render a nested dict as an ASCII tree.

    Modifies ``lines`` in place, appending tree connectors with
    appropriate indentation for each depth level.

    Args:
        node: The current dictionary node to render (subtree).
        lines: Accumulator list for output lines (modified in place).
        prefix: Indentation prefix for the current depth level.
    """
    items: list[tuple[str, bool]] = []
    for name, child in node.items():
        items.append((name, isinstance(child, dict)))
    items.sort(key=lambda x: (not x[1], x[0].lower()))

    for i, (name, is_dir) in enumerate(items):
        is_last = i == len(items) - 1
        connector = "└── " if is_last else "├── "
        lines.append(f"{prefix}{connector}{name}" + ("/" if is_dir else ""))
        if is_dir:
            _render_tree(
                node[name],
                lines,
                prefix + ("    " if is_last else "│   "),
            )


def _format_dir_agents(dirpath: str, files: list[dict]) -> list[str]:
    """Format AGENTS.md content for a single subdirectory.

    Generates a header, file table, and optional symbols section
    for the given directory's files.

    Args:
        dirpath: Relative path of the subdirectory (e.g. ``"src/treeva"``).
        files: List of file entry dictionaries for files in this directory.

    Returns:
        Lines of the AGENTS.md section, wrapped between generator markers.
    """
    header = f"# {dirpath}/ — Agent Reference"
    table_header = "| File | Language | Lines |"
    sep = "|------|----------|-------|"

    rows: list[str] = [header, "", table_header, sep]
    for f in sorted(files, key=lambda x: x["filename"]):
        rows.append(
            f"| `{f['filename']}` | {f['language']} | {_lines_cell(f)} |"
        )
    rows.append("")

    has_symbols = any(f["symbols"] for f in files)
    if has_symbols:
        rows.append("### Symbols")
        rows.append("")
        for f in sorted(files, key=lambda x: x["filename"]):
            if not f["symbols"]:
                continue
            rows.append(f"#### `{f['filename']}`")
            for s in f["symbols"]:
                rows.append(
                    f"  - `{s['kind']}` `{s['name']}` "
                    f"({s['start']}-{s['end']})"
                )
            rows.append("")

    return _wrap_section(rows)


def _format_root_agents(
    project_root: Path,
    total_files: int,
    total_loc: int,
    lang_loc: dict[str, int],
    root_files: list[dict],
    all_dirs: list[str],
    dir_files: dict[str, list[dict]],
) -> list[str]:
    """Format AGENTS.md content for the project root.

    Generates the full root AGENTS.md including project overview,
    tech stack, directory structure tree, root files table, directory
    map, and agent rules.

    Args:
        project_root: Root path of the project.
        total_files: Total number of files discovered in the project.
        total_loc: Total lines of code across all files.
        lang_loc: Mapping from language name to total LOC.
        root_files: List of file entries for files in the project root.
        all_dirs: Sorted list of all subdirectory paths.
        dir_files: Full mapping from directory path to list of file entries.

    Returns:
        Lines of the root AGENTS.md section, wrapped between generator markers.
    """
    lines: list[str] = []
    lines.append(f"# {project_root.name} — Agent Reference")
    lines.append("")

    # ── Project Overview ──
    lines.append("## Project Overview")
    lines.append("")
    desc = _read_pyproject_field(project_root, "description")
    version = _read_pyproject_field(project_root, "version")
    if desc:
        lines.append(f"- **Description**: {desc}")
    if version:
        lines.append(f"- **Version**: {version}")
    lines.append(f"- **Total files**: {total_files}")
    lines.append(f"- **Total LOC**: {total_loc}")
    sorted_langs = sorted(lang_loc.items(), key=lambda x: x[1], reverse=True)
    for lang, loc in sorted_langs:
        pct = (loc / total_loc * 100) if total_loc > 0 else 0
        lines.append(f"- {lang}: {loc} LOC ({pct:.1f}%)")
    lines.append("")

    # ── Tech Stack ──
    lines.append("## Tech Stack")
    lines.append("")
    for lang, _ in sorted_langs:
        lines.append(f"- **{lang}**")
    pyproject = project_root / "pyproject.toml"
    if pyproject.exists():
        try:
            import tomllib

            data = tomllib.loads(pyproject.read_text())
            deps = data.get("project", {}).get("dependencies", [])
            if deps:
                for dep in deps:
                    lines.append(f"  - {dep}")
        except Exception:
            pass
    lines.append("")

    # ── Directory Structure ──
    lines.append("## Directory Structure")
    lines.append("")
    tree = _build_file_tree(project_root, dir_files)
    lines.extend(tree)
    lines.append("")

    # ── Root Files ──
    if root_files:
        lines.append("## Root Files")
        lines.append("")
        table_header = "| File | Filetype | Description | Lines |"
        sep = "|------|----------|-------------|-------|"
        lines.append(table_header)
        lines.append(sep)
        for f in sorted(root_files, key=lambda x: x["filename"]):
            lines.append(
                f"| `{f['filename']}` | {_category_label(f)} "
                f"| {_root_description(f['filename'])} "
                f"| {_lines_cell(f)} |"
            )
        lines.append("")

    # ── Directory Map ──
    if all_dirs:
        lines.append("## Directory Map")
        lines.append("")
        lines.append("| Directory | Description |")
        lines.append("|-----------|-------------|")
        for d in all_dirs:
            lines.append(f"| `{d}/` | Placeholder: AI-generated description |")
        lines.append("")

    # ── Agent Rules ──
    lines.append("## Agent Rules")
    lines.append("")
    lines.append(
        "1. Follow the code style and conventions reflected in the codebase."
    )
    lines.append("2. Use patterns consistent with existing implementations.")
    lines.append(
        "3. Keep symbols, function signatures, and types in sync with source."
    )
    lines.append(
        "4. When adding new code, match the dependency and import style of "
        "the surrounding module."
    )
    lines.append(
        "5. Respect the project's directory structure — each directory has "
        "a focused responsibility."
    )
    lines.append(
        "6. When using Version Control, i.e: git, you **MUST** follow the below commit message format for **EVERY** commit."
    )
    lines.append(" - format: `<type>(<scope>): <summary>`")
    lines.append(
        "- **type** (required): feat | fix | docs | style | refactor | perf "
        "| test | chore"
    )
    lines.append(
        "- **scope** (optional): affected area, e.g. ui, github, notes, deps"
    )
    lines.append("- **summary**: <= 50 chars, lowercase, NO trailing period")
    lines.append("- **body** (optional): explain WHY, wrapped at 72 chars")
    lines.append("- **footer** (optional): issues / breaking changes")

    return _wrap_section(lines)


def _read_pyproject_field(project_root: Path, field: str) -> str:
    """Read a field from the project's pyproject.toml (project table).

    Args:
        project_root: Root path of the project.
        field: The field name to read from the ``[project]`` table.

    Returns:
        The field value as a string, or an empty string if the field
        is not found or the file cannot be read.
    """
    pyproject = project_root / "pyproject.toml"
    if pyproject.exists():
        try:
            import tomllib

            data = tomllib.loads(pyproject.read_text())
            val = data.get("project", {}).get(field, "")
            if val:
                return val
        except Exception:
            pass
    return ""
