"""Mapping from recognised file types to their typical file extensions."""

from .enums import FileType

FILE_EXTENSIONS: dict[FileType, list[str]] = {
    FileType.PYTHON: [".py"],
    FileType.JAVASCRIPT: [".js", ".jsx"],
    FileType.TYPESCRIPT: [".ts", ".tsx"],
    FileType.JAVA: [".java"],
    FileType.CPP: [".cpp", ".hpp", ".cc", ".cxx"],
    FileType.C: [".c", ".h"],
    FileType.CSHARP: [".cs"],
    FileType.GO: [".go"],
    FileType.RUST: [".rs"],
    FileType.RUBY: [".rb"],
    FileType.PHP: [".php"],
    FileType.SWIFT: [".swift"],
    FileType.KOTLIN: [".kt", ".kts"],
    FileType.SCALA: [".scala"],
    FileType.GROOVY: [".groovy"],
    FileType.PERL: [".pl"],
    FileType.R: [".r"],
    FileType.LUA: [".lua"],
    FileType.DART: [".dart"],
    FileType.ELIXIR: [".ex", ".exs"],
    FileType.CLOJURE: [".clj", ".cljs"],
    FileType.HASKELL: [".hs"],
    FileType.OCAML: [".ml", ".mli"],
    FileType.HTML: [".html", ".htm"],
    FileType.CSS: [".css"],
    FileType.SCSS: [".scss"],
    FileType.SASS: [".sass"],
    FileType.LESS: [".less"],
    FileType.SQL: [".sql"],
    FileType.BASH: [".sh"],
    FileType.ZSH: [".zsh"],
    FileType.FISH: [".fish"],
    FileType.POWERSHELL: [".ps1"],
    FileType.QML: [".qml"],
    FileType.JSON: [".json"],
    FileType.YAML: [".yaml", ".yml"],
    FileType.TOML: [".toml"],
    FileType.XML: [".xml"],
    FileType.INI: [".ini", ".cfg", ".conf"],
    FileType.PROPERTIES: [".properties"],
    FileType.ENV: [".env"],
    FileType.MARKDOWN: [".md"],
    FileType.RST: [".rst"],
    FileType.LATEX: [".tex"],
    FileType.ASCIIDOC: [".adoc"],
    FileType.ORG: [".org"],
    FileType.TXT: [".txt"],
    FileType.LOG: [".log"],
}
