from .enums import ConfigFile, DocFile, OtherCodeFile, ProgrammingLanguage

LANGUAGE_EXTENSIONS: dict[ProgrammingLanguage, list[str]] = {
    ProgrammingLanguage.PYTHON: [
        ".py",
        ".pyw",
        ".pyi",
        ".pyx",
        ".pxd",
        ".pxi",
    ],
    ProgrammingLanguage.JAVASCRIPT: [".js", ".mjs", ".cjs", ".jsx"],
    ProgrammingLanguage.TYPESCRIPT: [".ts", ".tsx"],
    ProgrammingLanguage.JAVA: [".java", ".class", ".jar"],
    ProgrammingLanguage.CPP: [
        ".cpp",
        ".hpp",
        ".cc",
        ".cxx",
        ".c++",
        ".hh",
        ".hxx",
        ".ipp",
    ],
    ProgrammingLanguage.C: [".c", ".h"],
    ProgrammingLanguage.CSHARP: [".cs", ".csx"],
    ProgrammingLanguage.GO: [".go"],
    ProgrammingLanguage.RUST: [".rs", ".rlib"],
    ProgrammingLanguage.SWIFT: [".swift"],
    ProgrammingLanguage.KOTLIN: [".kt", ".kts"],
    ProgrammingLanguage.RUBY: [".rb", ".rbw", ".gemspec", ".rake"],
    ProgrammingLanguage.PHP: [
        ".php",
        ".php3",
        ".php4",
        ".php5",
        ".php7",
        ".phps",
        ".phtml",
    ],
    ProgrammingLanguage.R: [".r", ".R", ".rdata", ".rds", ".rda"],
    ProgrammingLanguage.MATLAB: [".m", ".mat"],
    ProgrammingLanguage.SCALA: [".scala", ".sc"],
    ProgrammingLanguage.DART: [".dart"],
    ProgrammingLanguage.LUA: [".lua"],
    ProgrammingLanguage.PERL: [".pl", ".pm", ".t", ".pod"],
    ProgrammingLanguage.HASKELL: [".hs", ".lhs"],
    ProgrammingLanguage.ELIXIR: [".ex", ".exs"],
    ProgrammingLanguage.CLOJURE: [".clj", ".cljs", ".cljc", ".edn"],
    ProgrammingLanguage.ERLANG: [".erl", ".hrl"],
    ProgrammingLanguage.GROOVY: [".groovy", ".gvy", ".gy", ".gsh"],
    ProgrammingLanguage.FSHARP: [".fs", ".fsi", ".fsx"],
    ProgrammingLanguage.OCAML: [".ml", ".mli", ".mll", ".mly"],
    ProgrammingLanguage.FORTRAN: [
        ".f",
        ".for",
        ".f90",
        ".f95",
        ".f03",
        ".f08",
    ],
    ProgrammingLanguage.COBOL: [".cob", ".cbl", ".cobol"],
    ProgrammingLanguage.ADA: [".adb", ".ads"],
    ProgrammingLanguage.JULIA: [".jl"],
    ProgrammingLanguage.ZIG: [".zig"],
    ProgrammingLanguage.NIM: [".nim"],
    ProgrammingLanguage.V_LANG: [".v"],
    ProgrammingLanguage.CRYSTAL: [".cr"],
    ProgrammingLanguage.RACKET: [".rkt", ".rktl"],
    ProgrammingLanguage.HTML: [".html", ".htm", ".xhtml", ".html5"],
    ProgrammingLanguage.CSS: [".css"],
    ProgrammingLanguage.SASS: [".sass", ".scss"],
    ProgrammingLanguage.LESS: [".less"],
    ProgrammingLanguage.JSX: [".jsx"],
    ProgrammingLanguage.TSX: [".tsx"],
    ProgrammingLanguage.VUE: [".vue"],
    ProgrammingLanguage.SVELTE: [".svelte"],
    ProgrammingLanguage.SQL: [".sql", ".pgsql", ".mysql"],
    ProgrammingLanguage.PLSQL: [".pls", ".pld", ".plsql"],
    ProgrammingLanguage.TSQL: [".tsql"],
    ProgrammingLanguage.MYSQL: [".mysql"],
    ProgrammingLanguage.PGSQL: [".pgsql"],
    ProgrammingLanguage.BASH: [".sh", ".bash", ".bashrc", ".bash_profile"],
    ProgrammingLanguage.ZSH: [".zsh", ".zshrc", ".zshenv"],
    ProgrammingLanguage.FISH: [".fish"],
    ProgrammingLanguage.POWERSHELL: [".ps1", ".psm1", ".psd1"],
    ProgrammingLanguage.BATCH: [".bat", ".cmd"],
    ProgrammingLanguage.VBSCRIPT: [".vbs", ".vbe"],
}

# Config & Data files
CONFIG_EXTENSIONS: dict[ConfigFile, list[str]] = {
    ConfigFile.JSON: [".json", ".geojson", ".topojson"],
    ConfigFile.YAML: [".yaml", ".yml", ".yamlml"],
    ConfigFile.TOML: [".toml"],
    ConfigFile.XML: [".xml", ".xsd", ".xslt", ".dtd"],
    ConfigFile.INI: [".ini", ".cfg", ".conf", ".config", ".properties"],
    ConfigFile.CONF: [".conf"],
    ConfigFile.CFG: [".cfg"],
    ConfigFile.PROPERTIES: [".properties"],
    ConfigFile.ENV: [".env", ".envrc"],
    ConfigFile.DOTENV: [
        ".env",
        ".env.local",
        ".env.development",
        ".env.production",
    ],
    ConfigFile.MAKEFILE: ["Makefile", "makefile", "GNUMakefile"],
    ConfigFile.CMAKE: ["CMakeLists.txt", ".cmake"],
    ConfigFile.DOCKERFILE: ["Dockerfile", "Dockerfile.*"],
    ConfigFile.DOCKERCOMPOSE: [
        "docker-compose.yml",
        "docker-compose.yaml",
        "compose.yml",
    ],
    ConfigFile.PKGBUILD: ["PKGBUILD"],
    ConfigFile.PACKAGE_LOCK: ["package-lock.json"],
    ConfigFile.YARN_LOCK: ["yarn.lock"],
    ConfigFile.PNPM_LOCK: ["pnpm-lock.yaml"],
    ConfigFile.COMPOSER_LOCK: ["composer.lock"],
    ConfigFile.GEMFILE_LOCK: ["Gemfile.lock"],
    ConfigFile.CARGO_LOCK: ["Cargo.lock"],
    ConfigFile.POETRY_LOCK: ["poetry.lock"],
    ConfigFile.PIPFILE_LOCK: ["Pipfile.lock"],
    ConfigFile.UV_LOCK: ["uv.lock"],
    ConfigFile.MIX_LOCK: ["mix.lock"],
    ConfigFile.GIT: [
        ".git/",
        ".gitattributes",
        ".gitignore",
        ".gitmodules",
        ".gitconfig",
    ],
    ConfigFile.GITIGNORE: [".gitignore"],
    ConfigFile.GITATTRIBUTES: [".gitattributes"],
    ConfigFile.GITMODULES: [".gitmodules"],
    ConfigFile.GITCONFIG: [".gitconfig"],
    ConfigFile.GITBLAME: [".gitblame"],
    ConfigFile.SVN: [".svn/"],
    ConfigFile.HG: [".hg/"],
    ConfigFile.GITHUB_ACTIONS: [
        ".github/workflows/*.yml",
        ".github/workflows/*.yaml",
    ],
    ConfigFile.GITLAB_CI: [".gitlab-ci.yml"],
    ConfigFile.CIRCLE_CI: [".circleci/config.yml"],
    ConfigFile.JENKINS: ["Jenkinsfile"],
    ConfigFile.TRAVIS_CI: [".travis.yml"],
    ConfigFile.AZURE_PIPELINES: ["azure-pipelines.yml"],
    ConfigFile.BUILDKITE: ["buildkite.yml"],
    ConfigFile.DRONE: [".drone.yml"],
    ConfigFile.TEAMCITY: [".teamcity/"],
    ConfigFile.HELM: ["Chart.yaml", "values.yaml"],
    ConfigFile.KUBERNETES: [".yaml", ".yml"],  # Kubernetes manifests
    ConfigFile.TERRAFORM: [".tf", ".tfvars", ".tfstate"],
    ConfigFile.ANSIBLE: [".yml", ".yaml"],
    ConfigFile.PULUMI: ["Pulumi.yaml", "Pulumi.dev.yaml"],
}

# Documentation files
DOC_EXTENSIONS: dict[DocFile, list[str]] = {
    DocFile.MARKDOWN: [".md", ".markdown", ".mdown", ".mkd", ".mkdn"],
    DocFile.RST: [".rst"],
    DocFile.TEX: [".tex", ".latex", ".ltx"],
    DocFile.ADOC: [".adoc", ".asciidoc"],
    DocFile.ORG: [".org"],
    DocFile.MDX: [".mdx"],
    DocFile.TYPORA: [".typora"],
    DocFile.JSDOC: ["jsdoc.json", ".jsdocrc"],
    DocFile.TSDOC: ["tsdoc.json"],
    DocFile.PYDOC: [""],  # In-code docstrings
    DocFile.JAVADOC: [""],  # In-code comments
    DocFile.DOXYGEN: ["Doxyfile"],
    DocFile.TXT: [".txt", ".text"],
    DocFile.LOG: [".log"],
    DocFile.LICENSE: ["LICENSE", "LICENSE.md", "LICENSE.txt", "COPYING"],
    DocFile.README: ["README", "README.md", "README.txt", "README.rst"],
    DocFile.CONTRIBUTING: ["CONTRIBUTING.md", "CONTRIBUTING.rst"],
    DocFile.CHANGELOG: ["CHANGELOG.md", "CHANGELOG.txt", "HISTORY.md"],
    DocFile.TODO: ["TODO", "TODO.md", "TASKS.md"],
}

# Other code files
OTHER_CODE_EXTENSIONS: dict[OtherCodeFile, list[str]] = {
    OtherCodeFile.GRAPHQL: [".graphql", ".gql"],
    OtherCodeFile.PROTOBUF: [".proto"],
    OtherCodeFile.THRIFT: [".thrift"],
    OtherCodeFile.AVRO: [".avsc", ".avro"],
    OtherCodeFile.JSON_SCHEMA: [".schema.json"],
    OtherCodeFile.OPENAPI: [".yaml", ".yml", ".json"],  # openapi.yaml
    OtherCodeFile.RAML: [".raml"],
    OtherCodeFile.JINJA: [".j2", ".jinja", ".jinja2"],
    OtherCodeFile.HANDLEBARS: [".hbs", ".handlebars"],
    OtherCodeFile.MUSTACHE: [".mustache"],
    OtherCodeFile.EJS: [".ejs"],
    OtherCodeFile.PUG: [".pug"],
    OtherCodeFile.HAML: [".haml"],
    OtherCodeFile.SLIM: [".slim"],
    OtherCodeFile.ERB: [".erb"],
    OtherCodeFile.JSP: [".jsp"],
    OtherCodeFile.ASPX: [".aspx", ".ascx", ".master"],
    OtherCodeFile.JUPYTER: [".ipynb"],
    OtherCodeFile.RMD: [".rmd"],
    OtherCodeFile.QMD: [".qmd"],
    OtherCodeFile.STAN: [".stan"],
    OtherCodeFile.ASM: [".asm", ".s", ".S"],
    OtherCodeFile.NASM: [".nasm"],
    OtherCodeFile.MASM: [".masm"],
    OtherCodeFile.LLVM: [".ll"],
    OtherCodeFile.WASM: [".wasm"],
    OtherCodeFile.WAT: [".wat"],
    OtherCodeFile.CUDA: [".cu", ".cuh"],
    OtherCodeFile.OPENCL: [".cl", ".clh"],
    OtherCodeFile.METAL: [".metal"],
    OtherCodeFile.HLSL: [".hlsl", ".fx", ".hlsli"],
    OtherCodeFile.GLSL: [
        ".glsl",
        ".vert",
        ".frag",
        ".geom",
        ".tesc",
        ".tese",
        ".comp",
    ],
    OtherCodeFile.ANT: ["build.xml"],
    OtherCodeFile.MAVEN: ["pom.xml"],
    OtherCodeFile.GRADLE: [
        "build.gradle",
        "gradle.properties",
        "settings.gradle",
    ],
    OtherCodeFile.BAZEL: ["BUILD", "WORKSPACE", "BUILD.bazel"],
    OtherCodeFile.PANTS: ["pants.ini"],
    OtherCodeFile.SBT: ["build.sbt"],
    OtherCodeFile.GNU_MAKE: ["Makefile", "makefile"],
    OtherCodeFile.NINJA: ["build.ninja", ".ninja"],
    OtherCodeFile.MESON: ["meson.build", "meson_options.txt"],
    OtherCodeFile.HTACCESS: [".htaccess", ".htpasswd"],
    OtherCodeFile.NGNIX: ["nginx.conf"],
    OtherCodeFile.APACHE: ["httpd.conf", ".htaccess"],
    OtherCodeFile.TRAEFIK: ["traefik.yml", "traefik.yaml"],
    OtherCodeFile.CORS: [".cors"],
    OtherCodeFile.ESLINT: [
        ".eslintrc",
        ".eslintrc.js",
        ".eslintrc.json",
        ".eslintrc.yaml",
    ],
    OtherCodeFile.PRETTIER: [
        ".prettierrc",
        ".prettierrc.js",
        ".prettierrc.json",
        "prettier.config.js",
    ],
    OtherCodeFile.STYLELINT: [
        ".stylelintrc",
        ".stylelintrc.json",
        "stylelint.config.js",
    ],
    OtherCodeFile.RUBOCOP: [".rubocop.yml"],
    OtherCodeFile.PYLINT: [".pylintrc"],
    OtherCodeFile.FLAKE8: [".flake8"],
    OtherCodeFile.BLACK: ["pyproject.toml"],
    OtherCodeFile.REQUIREMENTS: [
        "requirements.txt",
        "requirements-dev.txt",
        "requirements-test.txt",
    ],
    OtherCodeFile.PACKAGE_JSON: ["package.json"],
    OtherCodeFile.CARGO_TOML: ["Cargo.toml"],
    OtherCodeFile.GO_MOD: ["go.mod"],
    OtherCodeFile.GO_SUM: ["go.sum"],
    OtherCodeFile.GEMFILE: ["Gemfile"],
    OtherCodeFile.PIPFILE: ["Pipfile"],
    OtherCodeFile.PYPROJECT: ["pyproject.toml"],
    OtherCodeFile.SETUP_PY: ["setup.py"],
    OtherCodeFile.SETUP_CFG: ["setup.cfg"],
    OtherCodeFile.COMPOSER_JSON: ["composer.json"],
    OtherCodeFile.PODSPEC: [".podspec"],
    OtherCodeFile.VSCODE: [".vscode/"],
    OtherCodeFile.EDITORCONFIG: [".editorconfig"],
    OtherCodeFile.VIM: [".vimrc", "vimrc", ".gvimrc", "_vimrc"],
    OtherCodeFile.EMACS: [".emacs", ".emacs.d/init.el"],
    OtherCodeFile.ATOM: [".atom/"],
    OtherCodeFile.SUBLIME: [".sublime-project", ".sublime-workspace"],
    OtherCodeFile.INTELLIJ: [".idea/"],
    OtherCodeFile.PYTEST: ["pytest.ini", "pytest.cfg", ".pytest.ini"],
    OtherCodeFile.JEST: ["jest.config.js", "jest.config.json"],
    OtherCodeFile.MOCHA: [".mocharc.js", ".mocharc.json"],
    OtherCodeFile.KARMA: ["karma.conf.js"],
    OtherCodeFile.CYPRESS: ["cypress.json", "cypress.config.js"],
    OtherCodeFile.PLAYWRIGHT: ["playwright.config.js", "playwright.config.ts"],
    OtherCodeFile.SELENIUM: ["selenium.properties"],
    OtherCodeFile.WEBPACK: ["webpack.config.js", "webpack.config.ts"],
    OtherCodeFile.VITE: ["vite.config.js", "vite.config.ts"],
    OtherCodeFile.ROLLUP: ["rollup.config.js"],
    OtherCodeFile.ESBUILD: ["esbuild.config.js"],
    OtherCodeFile.SNOWPACK: ["snowpack.config.js"],
    OtherCodeFile.PARCEL: [".parcelrc"],
    OtherCodeFile.MIGRATION: ["migration.sql"],
    OtherCodeFile.SEED: ["seed.sql"],
    OtherCodeFile.SCHEMA: ["schema.sql"],
    OtherCodeFile.PRISMA: ["schema.prisma"],
    OtherCodeFile.SEQUELIZE: [".sequelizerc"],
    OtherCodeFile.ALEMBIC: ["alembic.ini"],
    OtherCodeFile.FLYWAY: ["flyway.conf"],
    OtherCodeFile.LIQUIBASE: ["liquibase.properties"],
}

DEFAULT_EXCLUDES: set[str] = {
    # Version control
    ".git",
    ".svn",
    ".hg",
    ".bzr",
    # Python
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".nox",
    ".venv",
    "venv",
    "env",
    ".env",
    "site-packages",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    # Node / JavaScript / TypeScript
    "node_modules",
    ".npm",
    ".pnpm-store",
    ".yarn",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".parcel-cache",
    ".turbo",
    "coverage",
    # Java / Kotlin / Gradle
    ".gradle",
    "build",
    "out",
    "target",
    # Go / PHP / Ruby
    "vendor",
    ".bundle",
    "vendor/bundle",
    # C / C++ / CMake
    "cmake-build-debug",
    "cmake-build-release",
    "CMakeFiles",
    "CMakeCache.txt",
    "compile_commands.json",
    "Makefile",
    "*.o",
    "*.obj",
    "*.so",
    "*.dll",
    "*.exe",
    "*.a",
    "*.lib",
    # Swift / Xcode
    ".build",
    "DerivedData",
    # Dart / Flutter
    ".dart_tool",
    ".flutter-plugins",
    ".flutter-plugins-dependencies",
    ".packages",
    # Android / .NET
    ".idea",
    "captures",
    "bin",
    "obj",
    ".vs",
    # IDEs / Editors
    ".vscode",
    "*.iml",
    "*.suo",
    "*.user",
    "*.swp",
    "*.swo",
    "*~",
    # OS junk
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
    # Logs / temp
    "*.log",
    "*.tmp",
    "*.temp",
    "tmp",
    "temp",
    # Caches
    ".cache",
    ".sass-cache",
    ".eslintcache",
    # Distribution / build output
    "dist",
    "release",
    "debug",
    # Misc
    ".history",
}
